name: Simple React CI CD Pipeline workflow
on:
  push:
    branches:
      - master
      - main
  




jobs: 
    build_and_test:
        runs-on: ubuntu-latest
        
        
        steps:
          - name: "setup Node JS"
            uses: actions/setup-node@v2
            with:
              node-version: '21'

          - name: "check Node Version"
            run: node --version
          - name: "Clone the repository"
            uses: actions/checkout@v2
          
          - name: "list Directories"
            run: ls -la
              
        
          - name: "Install dependencies"
            run: npm install

          - name: "List Directories"
            run: ls -la


           
    